### ISSUE TITLE
License and the App Store

### ISSUE THREAD

**Issue by anthonylavado** [acvigue/JellyfinPlayer#1]
Hey there!
Thanks again for creating this client for iOS/iPadOS. For this repository and the others associated with it, would you consider changing the license to MPL 2.0? 

In order to publish without concerns on the Apple App Store, and to still encourage giving back to the community, I would personally suggest the [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/FAQ/). There is a reference page on [ChooseALicense.com](https://choosealicense.com/licenses/mpl-2.0/) that provides a good overview as to what it covers. It's how we at Jellyfin have chosen to license the [macOS wrapper](https://github.com/jellyfin/jellyfin-server-macos ) and our own [iOS App](https://github.com/jellyfin/jellyfin-expo).  Doing this early also avoids having to contact each future contributor for their approval if you decide to change your license later.

If you have any questions, just let me know! 🙂

**Comment by anthonylavado** [comment]
( A brief explainer of the reasoning: The GPL is directly incompatible because when you publish on the App Store, Apple signs the app and places usage restrictions on it. The MPL allows this type of usage, while still require that code changes be shared back. It's what VLC uses on iOS as well.)

**Comment by acvigue** [comment]
I had no idea! Thanks for bringing that up and I'll get right to changing that.
