### ISSUE TITLE
Error: Couldn't connect to server

### ISSUE THREAD

**Issue by haykkh** [acvigue/JellyfinPlayer#2]
When I try to connect to my home server I get `Error: Couldn't connect to server`.

Tested on the official Jellyfin app, browser, and Infuse, all of which work. 

## Notable 

-  My home server is https only
-  It's set up with a custom domain
    -  https://jellyfin.custom.domain

**Comment by haykkh** [comment]
After some testing it seems the issue was me omitting the port number in the server url section. 

What works:
- https://jellyfin.custom.domain:443

What doesn't work:
- https://jellyfin.custom.domain/
- http://jellyfin.custom.domain:443
- jellyfin.custom.domain:443


I would suggest changing it so that when a user inputs a url with https:// it auto defaults to using port 443

**Comment by acvigue** [comment]
HTTPS defaults to 443. Try omitting the slash in the link at the end

What works for me:
https://play.domain.me
https://play.domain.me:443
http://host:8096
host:8097

**Comment by acvigue** [comment]
Should be fixed in 197847c486ef7470f32e79cbdd11b99fbf3d48a6
